export const FNBC_LOGO = require('@/assets/images/fnbc-logo.png');

export const ICONS = {
  airtime: require('@/assets/icons/airtime.svg'),
  atm: require('@/assets/icons/atm.svg'),
  bag: require('@/assets/icons/bag.svg'),
  bell: require('@/assets/icons/bell.svg'),
  bill: require('@/assets/icons/bill.svg'),
  bolt: require('@/assets/icons/bolt.svg'),
  copy_black: require('@/assets/icons/copy_black.svg'),
  copy_white: require('@/assets/icons/copy_white.svg'),
  currency_exchange: require('@/assets/icons/currency_exchange.svg'),
  events: require('@/assets/icons/events.svg'),
  face_id: require('@/assets/icons/faceid.svg'),
  loan: require('@/assets/icons/loan.svg'),
  marker: require('@/assets/icons/marker.svg'),
  person: require('@/assets/icons/person.svg'),
  qr_code: require('@/assets/icons/qr_code.svg'),
  qr_code1: require('@/assets/icons/qr_code1.svg'),
  receipt1: require('@/assets/icons/receipt1.svg'),
  search: require('@/assets/icons/search.svg'),
  share: require('@/assets/icons/share.svg'),
  statement: require('@/assets/icons/statement.svg'),
  support_agent: require('@/assets/icons/support_agent.svg'),
  transfer: require('@/assets/icons/transfer.svg'),
  utilities: require('@/assets/icons/utilities.svg'),
}
